<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Authentification MVC</title>
  <link rel="stylesheet" href="assets/styles/style.css">
</head>

<body>
  <header>
    <nav>
      <ul>
        <li><a href="index.php?route=connexion">Connexion</a></li>
        <li><a href="index.php?route=inscription">Inscription</a></li>
        <li><a href="index.php?route=espace-perso">Espace Perso</a></li>
      </ul>
    </nav>
  </header>
  <hr>
  <?php
  switch ($route) {
    case 'connexion':
      require './templates/auth/login.phtml';
      break;
    case 'inscription':
      require './templates/auth/register.phtml';
      break;
    case 'espace-perso':
      require './templates/auth/espace_perso.phtml';
      break;
    case 'notConnected':
      require './templates/auth/not_connected.phtml';
      break;
    case 'alreadyConnected':
      require './templates/auth/already_connected.phtml';
      break;
    default:
      require './templates/notFound.phtml';
      break;
  }
  ?>

</body>

</html>

</html>