<main>
  <h1>Formulaire d'inscription</h1>

  <form action="index.php?route=check-inscription" method="POST">

    <label for="email">Adresse email :</label>
    <input type="text" id="email" name="email" required><br>

    <label for="password">Mot de passe :</label>
    <input type="password" id="password" name="password" required><br>

    <label for="confirm_password">Confirmez votre mot de passe :</label>
    <input type="password" id="confirm_password" name="confirm_password" required><br>



    <input type="submit" value="S'inscrire">
  </form>
</main>